#1. 인덱싱(indexing)
##- 리스트에 있는 갑스이 상대적인 주소(offset)로 값에 접근
##- 넘파이 배열의 인덱스 표현에는 ','을 지원함
## ex) '[행],[열]' 또는 '[행,열]' 형태
## -3차원 텐서 이상은 shape에서 출력되는 랭크 순서대로 인덱싱에 접근함

#2.슬라이싱(slicing)
##- '인덱스'를 사용하여 리스트 일부를 잘라내어 반환
##- 넘파이 배열은 행과 열을 나눠 슬라이싱할 수 있음

In [1]:
import numpy as np

#인덱싱

In [4]:
x = np.array([[1,2,3],[4.5,5,6 ]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x[0][0]

1

In [6]:
x[0,0]

1

In [7]:
x[0][2]

3

In [8]:
x[0,2]

3

In [9]:
x[0,1] = 100

In [10]:
x

array([[  1, 100,   3],
       [  4,   5,   6]])

#슬라이싱

In [11]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [13]:
x[1,1:3]

array([7, 8])

In [14]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [16]:
x = np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
x[:,::2]
#x[:,시작,끝,간격]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [18]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

#1. arange
##- range함수와 같이 차례대로 값을 생성
##arange(시작 인덱스, 마지막 인덱스, 증가값)
##- range함수와 달리 증가값에 술수형이 입력되어도 값을 생성할 수 있음
##- 소수점 값을 주기적으로 생성할 때 유용함

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [21]:
range(10)

range(0, 10)

In [22]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [25]:
for i in np.arange(-5,5):
  print(i)

-5
-4
-3
-2
-1
0
1
2
3
4


In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [29]:
for i in range(0,5):
  print(i)

0
1
2
3
4


In [30]:
for i in range(0,5,0.5):
  print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
for i in np.arange(0,5,0.5):
  print(i)

0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5


#ones, zeros, empty

In [32]:
np.ones(shape=(5,2), dtype = np.int8)
#행렬 5행2열을 정수형 1로 채우기

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [33]:
np.zeros(shape=(2,2), dtype = np.float32)
#0으로 채우기

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [35]:
np.empty(shape=(2,4), dtype=np.float32)

array([[7.544185e-36, 0.000000e+00, 0.000000e+00, 0.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00]],
      dtype=float32)

In [36]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.ones_like(x)
#x와 같은 배열의 모습에 값만 1로 채우기

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.zeros_like(x)
#x와 같은 배열의 모습에 값만 0로 채우기

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.empty_like(x)

array([[44828050,        0,        0,        0],
       [       0,        0,        0,        0],
       [       0,        0,        0,        0]])

In [40]:
np.identity(n=5, dtype = int)
#단위행렬 만들기

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [43]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.diag(matrix)
#대각선 출력

array([0, 4, 8])

In [47]:
np.diag(matrix,k=1)
#대각선 한칸 뒤부터 출력

array([1, 5])

#7. 통계 분석 함수

In [53]:
np.random.uniform(0,5,10)
#0부터 5사이 랜덤 실수 10개
#균등분포

array([0.39953688, 1.99864888, 0.8778947 , 2.85423123, 1.36631939,
       0.79524063, 0.65270869, 0.97077079, 3.74701502, 0.94360968])

In [51]:
np.random.normal(0,2,10)
#0부터 2사이 랜덤 실수 10개
#정규분포

array([-0.76596558, -0.85137799,  1.74830606,  3.06644996,  0.43886697,
       -1.72932061, -2.43346309,  0.11468295, -2.36349764,  0.16654544])

#8. 넘파이 배열 연산

In [54]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
test_array.sum()
#배열의 값들의 합

55

In [56]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
test_array.sum(axis = 0)
#세로로 합

array([15, 18, 21, 24])

In [59]:
test_array.sum(axis = 1)
#가로로 합

array([10, 26, 42])

In [60]:
test_array.mean(axis = 0)
#세로로 평균

array([5., 6., 7., 8.])

In [61]:
test_array.mean(axis = 1)
#가로로 평균

array([ 2.5,  6.5, 10.5])

In [62]:
np.sqrt(test_array)
#루트 씌우기(제곱근)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

#2. 연결 함수

In [65]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [66]:
np.vstack((v1,v2))
#수직으로 쌓기

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.hstack((v1,v2))
#수평으로 쌓기

array([1, 2, 3, 4, 5, 6])

In [68]:
np.hstack((v2,v1))
#순서 다르게 하면 다르게 쌓임

array([4, 5, 6, 1, 2, 3])

In [73]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
#세로로

In [74]:
v1

array([[1],
       [2],
       [3]])

In [75]:
v2

array([[4],
       [5],
       [6]])

In [76]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
np.vstack((v1,v2))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [78]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2),axis=0)
#2차원 배열 2개를 연결

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [80]:
v2

array([[5],
       [6]])

In [82]:
np.concatenate((v1,v2),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])