#넘파이
##파이썬의 고성능 과학 계산용 라이브러리
##벡터 + 행렬 -> 선형대수의 표현볍을 코드로 처리

#1. 빠른 속도, 효율적인 메모리 사용
###- 데이터를 메모리에 할당하는 방식이 기존과 다름
#2. 반복문을 사용하지 않음
###- 연산할 때 병렬로 처리
###- 함수를 한 번에 많은 요소에 적용함
#3. 다양한 선형대수 관련 함수 제공
#4. 다른 언어와 통합 사용 가능

##넘파이는 파이썬 설치 시 자동으로 설치되나요?
###코랩에서는 사용자들이 주로 사용하는 모듈과 패키지들이 이미 설치되어 있어 편의성을 제공
###PC : 오리지널 파이썬을 설치한다면 넘파이 패키지를 별도로 설치해야 함
###아나콘다(Anaconda) : 넘파이를 포함한 필수 모듈과 패키지들이 함께 설치됨

#1. 넘파이 배열(ndarray)
###- 넘파이에서 '텐서 데이터'를 다루는 객체
#2. 텐서(tensor)
###- 랭크(Rank)에 따라 이름이 다름
### Rank 0 : 스칼라(scalar) 7
### Rank 1 : 벡터(vector) [10,10]
### Rank 2 : 행렬(matrix) [[10,10],[15,15]]
### Rank 3 : 3차원 텐서(3-order tensor) [[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]]
### Rank n : n차원 텐서

In [1]:
import numpy as np


In [2]:
test_array = np.array([1,4,5,8], float)

In [3]:
test_array

array([1., 4., 5., 8.])

In [4]:
test_list = [[1,4,5,8],[1,4,5]]
test_list

[[1, 4, 5, 8], [1, 4, 5]]

In [5]:
np.array(test_list,float)
#하나의 데이터 타입만 지원

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [6]:
type(test_array[3])

numpy.float64

#3. 배열의 생성

In [8]:
test_array = np.array([1,4,5,"8"],float)
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array[3])
#배열 8의 데이터 타입

numpy.float64

In [10]:
test_array.dtype
#배열의 데이터 타입

dtype('float64')

In [12]:
test_array.shape
#배열의 구조

(4,)

In [14]:
matrix = [[1,2,5,8],[1,2,5,8]]
matrix

[[1, 2, 5, 8], [1, 2, 5, 8]]

In [15]:
np.array(matrix,int).shape

(2, 4)

In [16]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
matrix

[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]

In [17]:
np.array(matrix,int).shape

(3, 4)

In [19]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]

In [20]:
np.array(tensor_rank3,int).shape

(3, 3, 4)

In [23]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3,int).shape

(4, 3, 4)

In [27]:
np.array(tensor_rank3,int).ndim
#3차원

3

In [28]:
np.array(tensor_rank3,int).size
#요소 숫자 4개가 3묶음씩 4줄 : 4 * 3 * 4

48

In [30]:
np.array([[1,2,3.5],[4,5,6.5]],dtype = int)
#자료형 정수

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.array([[1,2,3.5],[4,5,6.5]],dtype = float)
#자료형 실수

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [32]:
import sys
np.array([[1,2,3.5],[4,5,6.5]],dtype = np.float64).itemsize
#자료형 64비트 선언시 8바이트 차지함

8

In [33]:
np.array([[1,2,3.5],[4,5,6.5]],dtype = np.float32).itemsize

4

#4. 배열의 구조 다루기

In [34]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [35]:
x.shape

(2, 4)

In [36]:
x.reshape(-1)
#행렬을 1줄로 바꾸기

array([1, 2, 5, 8, 1, 2, 5, 8])

In [38]:
x= np.array(range(8))
x
#range(8) : 0부터 7까지

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [40]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [41]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
x.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
x.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7])