#연산함수
##- 배열 내부 연산을 지원하는 함수
#축
##- 배열의 랭크가 증가할 때마다 새로운 축이 추가되어 차원 증가


In [1]:
import numpy as np
test_array = np.arange(1,11)
#1부터 10까지
test_array.sum()
#합 : 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10

55

#요소별 연산
##- 같은 배열의 구조일 때 요소별 연산
##- 두 배열의 구조가 동일할 경우 같은 인덱스 요소들끼리 연산
## 1, 2, 3, 4, 5
## *
## 1, 2, 3, 4, 5
##= 1, 4, 9, 16, 25


In [5]:
arr1 = np.arange(1,6)
arr2 = np.arange(1,6)
print(arr1*arr2)
print(arr1 + arr2)

[ 1  4  9 16 25]
[ 2  4  6  8 10]


#배열간 곱셈 연산
##- 요소별 연산과 벡터의 내적 연산 가능 : 두 배열 간의 곱셈
##- 두 개의 행렬에서 첫 번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야 함
##- m*n행렬과 n*l행렬, 벡터의 내적 연산하면 m*l의 행렬 생성

#브로드캐스팅 연산
##- 하나의 행렬과 스칼라값들 간의 연산
##- 행렬과 벡터 간의 연산

In [7]:
print(arr1)
print(arr1 + 3)

[1 2 3 4 5]
[4 5 6 7 8]


#3. 사칙연산 함수

In [8]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [11]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [15]:
x1 = np.arange(1,7).reshape(2,3)
x2 = x1.copy().reshape(3,2)
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
x1.dot(x2)
#내적

array([[22, 28],
       [49, 64]])

In [19]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
x // 3
#3으로 나눈 몫

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [23]:
x ** 2
#제곱

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [24]:
x % 3
#3으로 나눈 나머지

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [25]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [27]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

#비교 연산
##- 연산결과를 불린형(Boolean Type)을 가진 배열로 추출
#브로드캐스팅 비교 연산
##- 하나의 스칼라 값과 벡터 간의 비교 연산은 벡터 내 전체 요소에 적용

In [28]:
x = np.array([4,3,2,6,8,5])
x > 3

array([ True, False, False,  True,  True,  True])

#4. 비교 연산과 데이터 추출

In [32]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x > y

array([False,  True, False])

In [35]:
x = np.array([4,3,2,6,8,5])

In [36]:
(x>3).all()

False

In [37]:
(x>3).any()

True

In [38]:
x < 10

array([ True,  True,  True,  True,  True,  True])

In [39]:
(x < 10).any()

True

In [40]:
(x < 10).all()

True

In [41]:
np.where(x>5)
#5보다 큰 값의 인덱스 출력

(array([3, 4]),)

In [42]:
print(x[3],x[4])

6 8


In [43]:
np.where(x>5,10,20)
#5보다 크면 10, 작으면 20으로 출력

array([20, 20, 20, 10, 10, 20])

In [44]:
x

array([4, 3, 2, 6, 8, 5])

In [45]:
np.argsort(x)
#작은 순서대로 인덱스 출력
#작은 순서 : 2, 3, 4, 5, 6, 8
#인덱스 값 : 2, 1, 0, 5, 3, 4

array([2, 1, 0, 5, 3, 4])

In [46]:
np.argmax(x)
#가장 큰 값의 인덱스 값

4

In [47]:
np.argmin(x)
#가장 작은 값의 인덱스 값

2

#불린 인덱스(boolean index)
##- 배열에 있는 값들을 반환할 특정 조건을 불린형의 배열에 넣어서 추출
# 1. 인덱스에 들어가는 배열
##- 불린형이어야 함
# 2. 배열의 구조
##- 불린형 배열과 추출 대상이 되는 배열의 구조가 같아야 함
#팬시 인덱스(Fancy Index)
##- 정수형 배열의 값을 사이ㅛㅇ하여 해당 정수의 인덱스에 위치한 값을 반환
# 1. 인덱스에 들어가는 배열
##- 정수로만 구성되어야 함
# 2. 배열의 구조
##- 정수 값의 범위는 대상이 되는 배열이 가지는 인덱스 범위 내 대상이 되는 배열과 인덱스 배열의 구조가 같을 필요는 없음


# 인덱스를 활용한 데이터 추출

In [49]:
x

array([4, 3, 2, 6, 8, 5])

In [51]:
cond = x>3
# = : 오른쪽 내용을 왼쪽에 저장시킨다
# == : 왼쪽 내용과 오른쪽 내용이 같다
cond

array([ True, False, False,  True,  True,  True])

In [52]:
x[cond]
#cond에서 true값만 출력

array([4, 6, 8, 5])

In [53]:
x.shape

(6,)

In [54]:
cond.shape

(6,)

In [56]:
x

array([4, 3, 2, 6, 8, 5])

In [55]:
cond = np.array([1,2,0,2,2,2],int)
x[cond]
#x[1] x[2] x[0] x[2] x[2] x[2]

array([3, 2, 4, 2, 2, 2])

In [57]:
x.take(cond)

array([3, 2, 4, 2, 2, 2])

In [58]:
coffee = np.array([[4000,4500,5000,5500],[2,1,3,2]])
price = coffee[0]*coffee[1]
price.sum()

38500

In [59]:
price = np.array([4000,4500,5000,5500])
count = np.array([2,1,3,2])
result = price * count
result

array([ 8000,  4500, 15000, 11000])

In [60]:
result.sum()

38500